// Documented Muse TUI commands. Skills from skill/list extend this catalog at runtime.
const descriptions = {
  new: "Start a fresh conversation",
  clear: "Start a fresh conversation",
  name: "Rename this conversation",
  resume: "Find a retained conversation",
  fork: "Branch the current conversation",
  rewind: "Branch from an earlier message",
  side: "Start a side conversation",
  btw: "Ask a side question",
  compact: "Summarize context",
  recap: "Summarize recent activity",
  copy: "Copy the last response",
  export: "Export a conversation or trajectory",
  goal: "Manage the session goal",
  loop: "Schedule a recurring prompt",
  tasks: "Inspect background tasks",
  subagents: "Inspect native agents",
  stop: "Stop background work",
  workflows: "Inspect agent workflows",
  models: "Choose a model",
  effort: "Set reasoning effort",
  permissions: "Choose permission controls",
  settings: "Open settings",
  theme: "Choose appearance",
  mcp: "Inspect MCP servers and tools",
  skills: "Browse project skills",
  plugins: "Manage plugin bundles",
  memory: "Inspect project memory",
  help: "Commands and shortcuts",
  keymap: "Native keyboard shortcuts",
  status: "Inspect session status",
  usage: "Subscription usage",
  voice: "Inspect native voice state",
  feedback: "Send feedback through Muse CLI",
  login: "Connect your Muse account",
  logout: "Sign out through Muse CLI",
  terminal: "Open the native terminal",
  agents: "Inspect agents in the desktop",
  notifications: "Notification preferences",
};
const desktop = new Set([
  "new",
  "clear",
  "name",
  "resume",
  "fork",
  "compact",
  "copy",
  "subagents",
  "tasks",
  "workflows",
  "models",
  "effort",
  "permissions",
  "settings",
  "theme",
  "mcp",
  "skills",
  "help",
  "status",
  "usage",
  "login",
  "terminal",
  "agents",
  "notifications",
]);
module.exports = Object.entries(descriptions).map(([name, description]) => ({
  name,
  description,
  route: desktop.has(name) ? "desktop" : "native",
  source: "Muse CLI",
}));
